### ISSUE TITLE
Rescheduling final demonstration 

### ISSUE THREAD

**Issue by charlesalec** [rug-oop/2019_assignments#12]
Dearest TAs

Due to circumstances out of my control, I won't be in Groningen from the 23rd onwards.
Would it be possible to reschedule the final demonstration for an earlier date? 

Thank you so much!
Charles

**Comment by ghidirimschi** [comment]
Dear Charles,
Perhaps you could move the issue to your private repository? (so that you can both have more intimacy with the TA responsible for your group and also avoid involving people that have no connection to your problem). I expect you will also get an answer much faster if you do so.

**Comment by andrewlalis** [comment]
Closing this issue for now on the assumption that the conversation has been carried over to the private team repository.
