### ISSUE TITLE
[RESOLVED] Card Game Multi-Threading

### ISSUE THREAD

**Issue by varanauskas** [rug-oop/2019_assignments#14]
I have noticed that multi-threading is forbidden in card-game assignment on reader, however,  that makes it nearly impossible to create a multiplayer game.

Would it be possible to make the **multi-threaded** game server as a **seperate** independent submodule (runnable only with command line arguments), or even a different java project, and make a **single-threaded** client that would comply with all of the requirements (MVC, Observer, etc.) thus still managing to make a multiplayer card game?

**Comment by ana-roman** [comment]
You dont have to over-complicate the assignment. What is meant with _multiplayer_ game is not that we expect to you a Server-Client structure to which you can connect from different machines over a network, but simply that you have two different player (objects) that have, for example, some kind of score. Such a game can be played on the same screen, and different players can take actions  on their turns. 

As mentioned, multi-threading is not expected and thus, unnecessary. You will have enough time to practice around with threads in Advanced OOP in Semptember :+1:
