### ISSUE TITLE
Release date assignments

### ISSUE THREAD

**Issue by IsaiahvH** [rug-oop/2019_assignments#15]
Hello,

I notice that the lab assignments on github are release quite late.
It would be preferable if the assignments repository on github was updated a week in advance, so that we can start immediately from the repository a week ahead, instead of starting without and merging the files later.

Kind regards,

**Comment by ana-roman** [comment]
Hello, 
Our excuses for publishing the previous assignment rather late - we will make sure that the files for the next ones are ready at the same time with the previous deadline. 
However, there will not be any given code for Graph Editor (the only thing you will receive for that is the folder structure), so for that one you can start working asap :) 
Good luck!
