### ISSUE TITLE
Pull request on cmd Windows

### ISSUE THREAD

**Issue by RalucaStefan** [rug-oop/2019_assignments#17]
Hey, would it be possible to tell me if there is a way to pull a request on Windows? I cannot seem to be able to find the right commands in cmd

**Comment by andrewlalis** [comment]
If you mean to create a pull request for your Github submission, this should be done on github.com. I am not aware of any way to create a pull request via command-line.

However, being on Windows, you can't really use the cmd for git in the first place, so if you aren't using the built-in IntelliJ support for git, you can get it for windows here: https://gitforwindows.org/

**Comment by andrewlalis** [comment]
You should create all pull requests on github.com. There's no way to do that locally.
