### ISSUE TITLE
Observable is deprecated

### ISSUE THREAD

**Issue by varanauskas** [rug-oop/2019_assignments#19]
According to [java docs](https://docs.oracle.com/javase/9/docs/api/java/util/Observable.html) Observable has been Deprecated.

Would it be possible for us to implement a similar functionality using [java.beans](https://docs.oracle.com/javase/9/docs/api/java/beans/package-summary.html) (mostly PropertyChangeListener)  in the place of Observable?

**Comment by Jari27** [comment]
The docs note that `Observable `is deprecated as of Java 9. We use java 1.8 (= 8). So it's not deprecated for our java version.

**Comment by varanauskas** [comment]
> The docs note that `Observable `is deprecated as of Java 9. We use java 1.8 (= 8). So it's not deprecated for our java version.

So using java.beans instead of Observable would not be allowed in this case?

**Comment by Jari27** [comment]
It says in the slides that it is possible but that Observable is fine for this assignment.
