### ISSUE TITLE
Graph editor deadline

### ISSUE THREAD

**Issue by theejazz** [rug-oop/2019_assignments#22]
Hi,

I was wondering what the final deadline is for the last assignment because there are currently two conflicting dates on Nestor. The latest announcement, 'Graph Editor Assignment Added', states it's 
9 AM on 12 June, yet the schedule has it for 5 PM on 19 June (which I imagine most students would very much appreciate).

Thanks in advance

**Comment by ana-roman** [comment]
You're right, 19 june :) announcement was fixed. Thanks!
