### ISSUE TITLE
Reader claims the GraphModel should implement Observer

### ISSUE THREAD

**Issue by theejazz** [rug-oop/2019_assignments#23]
Hi, I think I've found a mistake in the reader. On page 41, item 14, it states the following:

> When something in the graph changes, this also has to be shown in the graphical interface. [...] You should do this by making the GraphModel Observer and the GraphPanel Observer.

Surely, GraphModel should instead extend Observable for GraphPanel to be able to observe it. In fact, the link for 'Observer' in "...the GraphModel Observer and the..." links to the Oracle documentation for Observable.

**Comment by ana-roman** [comment]
Yes, you are right! Thank you for the notice!
