### ISSUE TITLE
New frame for GraphEditor

### ISSUE THREAD

**Issue by renzocuadra** [rug-oop/2019_assignments#24]
Section 10.3 in the reader says " Add an action that creates a new frame with exactly the same model. Changes made in one model should also appear in all the other frames". Does this mean the new frames are exact replicas of the model, so that they all show the same state of the graph at every step? Then every time you change something in the graph all frames would change in the same way.

**Comment by ana-roman** [comment]
Yes, that's what the requirement is :)
