### ISSUE TITLE
cloning and switching branches in intellij

### ISSUE THREAD

**Issue by merongy** [rug-oop/2019_assignments#3]
I am using IntelliJ for the assignment. 
I tried cloning with the terminal but I don't know how to proceed next... could you please help me?
<img width="762" alt="스크린샷 2019-04-23 13 38 06" src="https://user-images.githubusercontent.com/49649610/56578134-254cc500-65cd-11e9-8a90-ebb0bb1cf84e.png">

and when i try to clone it on intellij, i come to this
<img width="1512" alt="스크린샷 2019-04-23 13 05 02" src="https://user-images.githubusercontent.com/49649610/56578184-457c8400-65cd-11e9-908d-3731d6480803.png">

in both cases, i don't know what to do next.

**Comment by fabcancia** [comment]
I have the same problem, how did you solve it? 
Thanks

**Comment by Jari27** [comment]
To checkout a _new_ branch, use the -b flag, i.e. `git checkout -b development`. Git should automatically realise that there is a remote branch (i.e. on github) with the same name.

**Comment by fabcancia** [comment]
okay I have done it, but now I get this error.


![Screenshot at 2019-04-23 20-55-31](https://user-images.githubusercontent.com/47502249/56608145-657e6880-660a-11e9-829c-0840ddd9eb8b.png)

**Comment by Jari27** [comment]
That's expected. These methods are not implemented yet. The reader explains how you should implement them.
