### ISSUE TITLE
Cannot find symbol

### ISSUE THREAD

**Issue by keizerguy** [rug-oop/2019_assignments#5]
Hi, I'm trying to run _mvn integration-test_ after successfully building however, I am then prompted with the following error:
 ` COMPILATION ERROR :
[INFO] -------------------------------------------------------------
[ERROR] /C:/Users/<user>/2019_Team_45/helloWorld/src/test/java/nl/rug/oop/helloWorld/MemoryTest.java:[38,13] cannot find symbol
  symbol:   class Memory
  location: class MemoryTest
[ERROR] /C:/Users/<user>/2019_Team_45/helloWorld/src/test/java/nl/rug/oop/helloWorld/MemoryTest.java:[45,22] cannot find symbol
  symbol:   class Memory
  location: class MemoryTest`
Any idea as how to resolve this?

**Comment by nvbln** [comment]
I had a similar error. In order to solve it I added the tests to the package. The tests should then be able to find the class.

**Comment by CorineNijhof** [comment]
How did you 

> I had a similar error. In order to solve it I added the tests to the package. The tests should then be able to find the class.

How did you add the tests to the package?
