### ISSUE TITLE
Cannot resolve hasNextLine symbol

### ISSUE THREAD

**Issue by fabcancia** [rug-oop/2019_assignments#6]
We imported the import java.util.Scanner but it still does not recognize the scan.hasNextLine(). 
Does anyone have any idea how to solve this problem?
![Screenshot at 2019-04-24 12-20-20](https://user-images.githubusercontent.com/47502249/56652722-53dda500-668c-11e9-8ea3-814415cb223c.png)
![Screenshot at 2019-04-24 12-20-28](https://user-images.githubusercontent.com/47502249/56652723-53dda500-668c-11e9-87ab-951fe4b15de2.png)

**Comment by microwavekonijn** [comment]
Check your brackets on your main method and where you close them.

**Comment by fabcancia** [comment]
opsss that was dumb, sorry for the stupid question
